/** 后端真实系统状态 */
export interface SystemStatus {
  status: string;
  version: string;
  app_name: string;
  timestamp: string;
  mock_mode: boolean;
  auth_mode?: 'demo' | 'real';
  auth_adapter?: string;
  auth_configured?: boolean;
  production_auth_ready?: boolean;
  official_dataset_loaded: boolean;
  model_market_connected: boolean;
  model_market_adapter?: string;
  model_market_demo_mode?: boolean;
  model_market_configured?: boolean;
  model_market_status_message?: string;
  demo_result_mode: boolean;
  model_asset_repository_ready?: boolean;
  model_asset_total?: number;
  model_asset_by_source?: Record<string, number>;
  model_asset_by_domain?: Record<string, number>;
  model_asset_validation_issues?: number;
  retrieval_runtime_mode?: 'light' | 'competition_dense';
  dense_runtime_ready?: boolean;
  dense_requested?: boolean;
  dense_required?: boolean;
  dense_initialized?: boolean;
  dense_available?: boolean;
  dense_model?: string;
  dense_weight?: number;
  dense_embedding_dimension?: number;
  dense_expected_dimension?: number;
  dense_expected_revision?: string;
  dense_offline?: boolean;
  dense_manifest_required?: boolean;
  dense_manifest_verified?: boolean;
  dense_cache_ready?: boolean;
  dense_cache_hit?: boolean;
  dense_error_code?: string;
  llm_trace_enabled: boolean;
  llm_enabled: boolean;
  llm_provider: string;
  llm_model: string;
  llm_base_url_configured: boolean;
  llm_api_key_configured: boolean;
  llm_timeout_seconds: number;
  llm_max_retries: number;
  error?: string;
}
